export default {
  CREATE_GAME: "CREATE_GAME",
  UPDATE_GAME: "UPDATE_GAME",
  END_GAME: "END_GAME",

  LOAD_QUESTIONS: "LOAD_QUESTIONS",
  PICK_QUESTIONS: "PICK_QUESTIONS",

  CREATE_USER: "CREATE_USER",
  LOAD_USERS: "LOAD_USERS",
  UPDATE_USER: "UPDATE_USER",
};
